# This file is part of gfnff.
# SPDX-Identifier: LGPL-3.0-or-later

srcs += files(
  'math.f90',
  'types.f90',
  'neighbor.f90',
  'param_tables.f90',
  'bond_potential.f90',
  'param.f90',
  'param_io.F90',
  'geometry.f90',
  'fragments.f90',
  'strings.f90',
  'search.f90',
  'wsc.f90',
  'latticepoint.f90',
  'timer.f90',
)
