#!/usr/bin/env python3
# This file is part of gfnff.
# SPDX-Identifier: LGPL-3.0-or-later
"""Regenerate project_index.md from the sources.

The index maps files to the modules and procedures they define and records the
module dependency graph. It is generated rather than maintained so it cannot
drift from the tree -- run it after any change that moves code between files.

    test/tools/mkindex.py            write project_index.md
    test/tools/mkindex.py --check    exit 1 if the file is out of date
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "project_index.md")
SRC = os.path.join(ROOT, "src")

RE_MODULE = re.compile(r"^\s*module\s+([a-z]\w*)\s*$", re.I)
RE_PROG = re.compile(r"^\s*program\s+([a-z]\w*)\s*$", re.I)
RE_USE = re.compile(r"^\s*use\s*(?:,\s*intrinsic\s*::)?\s*([a-z]\w*)", re.I)
RE_PROC = re.compile(
    r"^\s*(?:(?:pure|elemental|recursive|impure|module)\s+)*"
    r"(?:(?:real|integer|logical|complex|character|double\s+precision|type)"
    r"\s*(?:\([^)]*\))?\s*)?"
    r"(subroutine|function)\s+([a-z]\w*)",
    re.I,
)
RE_END = re.compile(r"^\s*end\s+(subroutine|function)\b", re.I)
RE_INTERFACE = re.compile(r"^\s*(abstract\s+)?interface\b", re.I)
RE_END_INTERFACE = re.compile(r"^\s*end\s+interface\b", re.I)

# Directories that hold vendored constant tables; their contents are listed but
# not expanded, they would swamp the index with parameter arrays.
DATA_FILES = {"dftd3param.f90", "dftd4param.f90", "lebedev.f90"}


def scan(path):
    """Return (modules, procedures, uses, nlines) for one source file."""
    mods, procs, uses = [], [], set()
    depth_interface = 0
    with open(path, errors="replace") as fh:
        lines = fh.readlines()
    for line in lines:
        if line.lstrip().startswith("!"):
            continue
        if RE_INTERFACE.match(line):
            depth_interface += 1
            continue
        if RE_END_INTERFACE.match(line):
            depth_interface = max(0, depth_interface - 1)
            continue
        m = RE_MODULE.match(line)
        if m and m.group(1).lower() != "procedure":
            mods.append(m.group(1))
            continue
        m = RE_PROG.match(line)
        if m:
            mods.append(m.group(1) + " (program)")
            continue
        m = RE_USE.match(line)
        if m:
            uses.add(m.group(1).lower())
            continue
        if depth_interface:
            continue
        if RE_END.match(line):
            continue
        m = RE_PROC.match(line)
        if m:
            procs.append(m.group(2))
    return mods, procs, uses, len(lines)


def collect():
    entries = []
    for dirpath, dirnames, filenames in os.walk(SRC):
        dirnames.sort()
        for fn in sorted(filenames):
            if not fn.endswith((".f90", ".F90")):
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, ROOT)
            mods, procs, uses, n = scan(full)
            if fn in DATA_FILES:
                procs = []
            entries.append((rel, mods, procs, uses, n))
    return entries


def render(entries):
    own = [e for e in entries if os.path.basename(e[0]) not in DATA_FILES]
    data = [e for e in entries if os.path.basename(e[0]) in DATA_FILES]
    total = sum(e[4] for e in entries)
    data_lines = sum(e[4] for e in data)

    out = []
    out.append("# Source index")
    out.append("")
    out.append(
        "Generated by `test/tools/mkindex.py` -- do not edit by hand, "
        "rerun the script instead."
    )
    out.append("")
    out.append(
        f"{len(entries)} Fortran files, {total:,} lines, of which {data_lines:,} "
        f"({100 * data_lines // max(total, 1)} %) are vendored constant tables."
    )
    out.append("")

    # ── module -> file, for lookup ────────────────────────────────────────────
    out.append("## Modules")
    out.append("")
    out.append("| module | file | lines | procedures |")
    out.append("|---|---|---:|---:|")
    rows = []
    for rel, mods, procs, uses, n in entries:
        for m in mods:
            rows.append((m.lower(), m, rel, n, len(procs)))
    for _, m, rel, n, np_ in sorted(rows):
        out.append(f"| `{m}` | `{rel}` | {n} | {np_} |")
    out.append("")

    # ── per directory listing ─────────────────────────────────────────────────
    out.append("## Procedures by file")
    out.append("")
    lastdir = None
    for rel, mods, procs, uses, n in own:
        d = os.path.dirname(rel)
        if d != lastdir:
            out.append(f"### `{d}/`")
            out.append("")
            lastdir = d
        out.append(f"**`{os.path.basename(rel)}`** ({n} lines)"
                   + (f" -- `{'`, `'.join(mods)}`" if mods else ""))
        out.append("")
        if procs:
            out.append("> " + ", ".join(f"`{p}`" for p in procs))
        else:
            out.append("> _no procedures_")
        out.append("")

    if data:
        out.append("### Vendored data")
        out.append("")
        for rel, mods, procs, uses, n in data:
            out.append(f"- `{rel}` ({n:,} lines) -- `{'`, `'.join(mods)}`")
        out.append("")

    # ── dependency graph ──────────────────────────────────────────────────────
    defined = {m.lower(): rel for rel, mods, _, _, _ in entries for m in mods}
    out.append("## Module dependencies")
    out.append("")
    out.append("Internal `use` edges only; intrinsic and external modules are omitted.")
    out.append("")
    used_by = {}
    for rel, mods, procs, uses, n in entries:
        for u in uses:
            if u in defined:
                used_by.setdefault(u, set()).update(m.lower() for m in mods)
    out.append("| module | used by |")
    out.append("|---|---:|")
    for m in sorted(defined):
        n_users = len(used_by.get(m, ()))
        users = ", ".join(f"`{x}`" for x in sorted(used_by.get(m, ()))) or "_nothing_"
        out.append(f"| `{m}` ({n_users}) | {users} |")
    out.append("")
    return "\n".join(out) + "\n"


def main():
    text = render(collect())
    if "--check" in sys.argv:
        if not os.path.exists(OUT) or open(OUT).read() != text:
            print("project_index.md is out of date; run test/tools/mkindex.py")
            return 1
        return 0
    with open(OUT, "w") as fh:
        fh.write(text)
    print(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
